const fs = require('fs');

const file = '/Users/ankitanand/.gemini/antigravity/playground/azure-sun/src/data/games_data.json';
const data = JSON.parse(fs.readFileSync(file, 'utf8'));

const newWords = [
  { word: "Smile", forbidden: ["Happy", "Face", "Teeth", "Mouth", "Laugh"] },
  { word: "Dance", forbidden: ["Music", "Move", "Feet", "Party", "Song"] },
  { word: "Jump", forbidden: ["Up", "High", "Air", "Legs", "Hop"] },
  { word: "Sing", forbidden: ["Song", "Music", "Voice", "Loud", "Choir"] },
  { word: "Draw", forbidden: ["Picture", "Pencil", "Paper", "Art", "Sketch"] },
  { word: "Kiss", forbidden: ["Lips", "Love", "Mouth", "Romantic", "Face"] },
  { word: "Hug", forbidden: ["Arms", "Squeeze", "Love", "Hold", "Embrace"] },
  { word: "Run", forbidden: ["Fast", "Sprint", "Walk", "Legs", "Race"] },
  { word: "Swim", forbidden: ["Water", "Pool", "Ocean", "Wet", "Stroke"] },
  { word: "Sleep", forbidden: ["Bed", "Night", "Tired", "Dream", "Eyes"] },
  { word: "Dream", forbidden: ["Sleep", "Night", "Bed", "Mind", "Imagine"] },
  { word: "Cry", forbidden: ["Tears", "Sad", "Eyes", "Weep", "Unhappy"] },
  { word: "Laugh", forbidden: ["Funny", "Joke", "Smile", "Happy", "Haha"] },
  { word: "Read", forbidden: ["Book", "Words", "Page", "Library", "Story"] },
  { word: "Write", forbidden: ["Pen", "Pencil", "Paper", "Letter", "Word"] },
  { word: "Fly", forbidden: ["Bird", "Plane", "Air", "Sky", "Wings"] },
  { word: "Throw", forbidden: ["Ball", "Catch", "Arm", "Toss", "Pitch"] },
  { word: "Catch", forbidden: ["Throw", "Ball", "Hands", "Grab", "Hold"] },
  { word: "Breakfast", forbidden: ["Morning", "Food", "Eat", "Eggs", "Cereal"] },
  { word: "Lunch", forbidden: ["Noon", "Food", "Sandwich", "Eat", "Meal"] },
  { word: "Dinner", forbidden: ["Evening", "Food", "Eat", "Meal", "Night"] },
  { word: "Snack", forbidden: ["Eat", "Food", "Hungry", "Between", "Chips"] },
  { word: "Desert", forbidden: ["Sand", "Hot", "Dry", "Camel", "Sahara"] },
  { word: "Mountain", forbidden: ["High", "Climb", "Peak", "Snow", "Everest"] },
  { word: "Ocean", forbidden: ["Water", "Sea", "Waves", "Beach", "Blue"] },
  { word: "River", forbidden: ["Water", "Flow", "Stream", "Bank", "Boat"] },
  { word: "Lake", forbidden: ["Water", "Fresh", "Boat", "Fish", "Pond"] },
  { word: "Forest", forbidden: ["Trees", "Wood", "Nature", "Animals", "Green"] },
  { word: "Sand", forbidden: ["Beach", "Desert", "Castle", "Grains", "Dirt"] },
  { word: "Dirt", forbidden: ["Soil", "Earth", "Mud", "Ground", "Plant"] },
  { word: "Rock", forbidden: ["Stone", "Hard", "Mountain", "Pebble", "Mineral"] },
  { word: "Grass", forbidden: ["Green", "Lawn", "Yard", "Plant", "Mow"] },
  { word: "Star", forbidden: ["Sky", "Night", "Twinkle", "Bright", "Space"] },
  { word: "Planet", forbidden: ["Space", "Earth", "Mars", "Orbit", "System"] },
  { word: "Space", forbidden: ["Stars", "Planets", "Universe", "Rocket", "Astronaut"] },
  { word: "Alien", forbidden: ["Space", "UFO", "Green", "Mars", "Extraterrestrial"] },
  { word: "Ghost", forbidden: ["Scary", "Spirit", "White", "Haunted", "Boo"] },
  { word: "Skeleton", forbidden: ["Bones", "Skull", "Scary", "Halloween", "Body"] },
  { word: "Zombie", forbidden: ["Dead", "Brain", "Walk", "Scary", "Monster"] },
  { word: "Vampire", forbidden: ["Blood", "Bite", "Dracula", "Teeth", "Bat"] },
  { word: "Witch", forbidden: ["Broom", "Magic", "Spell", "Hat", "Cauldron"] },
  { word: "Magic", forbidden: ["Trick", "Wand", "Spell", "Illusion", "Wizard"] },
  { word: "Spell", forbidden: ["Magic", "Witch", "Words", "Curse", "Book"] },
  { word: "Castle", forbidden: ["King", "Queen", "Knight", "Fortress", "Building"] },
  { word: "Knight", forbidden: ["Armor", "Sword", "Horse", "Castle", "Fight"] },
  { word: "Dragon", forbidden: ["Fire", "Breathe", "Wings", "Scale", "Myth"] },
  { word: "Princess", forbidden: ["Girl", "Castle", "Crown", "Queen", "Dress"] },
  { word: "Queen", forbidden: ["King", "Crown", "Princess", "Royal", "Rule"] },
  { word: "King", forbidden: ["Queen", "Crown", "Royal", "Rule", "Throne"] },
  { word: "Sword", forbidden: ["Weapon", "Sharp", "Knight", "Blade", "Fight"] },
  { word: "Shield", forbidden: ["Protect", "Defend", "Knight", "Armor", "Sword"] },
  { word: "Bow", forbidden: ["Arrow", "Shoot", "String", "Weapon", "Target"] },
  { word: "Arrow", forbidden: ["Bow", "Shoot", "Target", "Point", "Quiver"] },
  { word: "Horse", forbidden: ["Ride", "Animal", "Saddle", "Gallop", "Neigh"] },
  { word: "Cow", forbidden: ["Bovine", "Milk", "Farm", "Animal", "Moo"] },
  { word: "Pig", forbidden: ["Mud", "Pink", "Oink", "Farm", "Bacon"] },
  { word: "Sheep", forbidden: ["Wool", "Baa", "Farm", "Flock", "White"] },
  { word: "Goat", forbidden: ["Horns", "Farm", "Animal", "Bleat", "Mountain"] },
  { word: "Chicken", forbidden: ["Egg", "Bird", "Farm", "Meat", "Cluck"] },
  { word: "Turkey", forbidden: ["Thanksgiving", "Bird", "GOBBLE", "Meat", "Holiday"] },
  { word: "Eagle", forbidden: ["Bird", "Fly", "Bald", "Sky", "America"] },
  { word: "Owl", forbidden: ["Night", "Bird", "Hoot", "Eyes", "Wise"] },
  { word: "Bear", forbidden: ["Brown", "Grizzly", "Animal", "Forest", "Honey"] },
  { word: "Wolf", forbidden: ["Howl", "Moon", "Dog", "Pack", "Forest"] },
  { word: "Fox", forbidden: ["Sly", "Red", "Animal", "Tail", "Smart"] },
  { word: "Deer", forbidden: ["Antlers", "Bambi", "Forest", "Animal", "Hunt"] },
  { word: "Lion", forbidden: ["Roar", "King", "Jungle", "Africa", "Mane"] },
  { word: "Tiger", forbidden: ["Stripes", "Orange", "Cat", "Jungle", "Roar"] },
  { word: "Monkey", forbidden: ["Banana", "Ape", "Swing", "Tree", "Jungle"] },
  { word: "Elephant", forbidden: ["Trunk", "Big", "Grey", "Africa", "Ivory"] },
  { word: "Giraffe", forbidden: ["Neck", "Tall", "Spots", "Africa", "Animal"] },
  { word: "Zebra", forbidden: ["Stripes", "Black", "White", "Africa", "Horse"] },
  { word: "Hippo", forbidden: ["Water", "Big", "Africa", "River", "Animal"] },
  { word: "Rhino", forbidden: ["Horn", "Grey", "Big", "Africa", "Animal"] },
  { word: "Kangaroo", forbidden: ["Jump", "Pouch", "Australia", "Animal", "Hop"] },
  { word: "Penguin", forbidden: ["Bird", "Ice", "Cold", "Black", "White"] },
  { word: "Whale", forbidden: ["Ocean", "Big", "Mammal", "Blowhole", "Sea"] },
  { word: "Shark", forbidden: ["Teeth", "Ocean", "Bite", "Fin", "Fish"] },
  { word: "Dolphin", forbidden: ["Smart", "Ocean", "Mammal", "Flipper", "Echo"] },
  { word: "Octopus", forbidden: ["Eight", "Legs", "Ocean", "Tentacles", "Ink"] },
  { word: "Crab", forbidden: ["Shell", "Ocean", "Claws", "Sand", "Walk"] },
  { word: "Lobster", forbidden: ["Red", "Ocean", "Claws", "Shell", "Eat"] },
  { word: "Shrimp", forbidden: ["Small", "Seafood", "Ocean", "Pink", "Cocktail"] },
  { word: "Shell", forbidden: ["Beach", "Sea", "Snail", "Hard", "Crab"] },
  { word: "Island", forbidden: ["Water", "Land", "Ocean", "Tropical", "Beach"] },
  { word: "Boat", forbidden: ["Water", "Ship", "Float", "River", "Sail"] },
  { word: "Ship", forbidden: ["Boat", "Ocean", "Cruise", "Water", "Sail"] },
  { word: "Sail", forbidden: ["Boat", "Wind", "Water", "Ship", "Mast"] },
  { word: "Pirate", forbidden: ["Ship", "Sail", "Treasure", "Eye", "Patch"] },
  { word: "Treasure", forbidden: ["Gold", "Pirate", "Chest", "Map", "Silver"] },
  { word: "Map", forbidden: ["Directions", "Paper", "Find", "Location", "Treasure"] },
  { word: "Gold", forbidden: ["Silver", "Metal", "Yellow", "Jewelry", "Valuable"] },
  { word: "Silver", forbidden: ["Gold", "Metal", "Grey", "Coin", "Jewelry"] },
  { word: "Diamond", forbidden: ["Ring", "Jewel", "Rock", "Expensive", "Engagement"] },
  { word: "Spider", forbidden: ["Web", "Bite", "Eight", "Insects", "Scary"] },
  { word: "Snake", forbidden: ["Hiss", "Slither", "Bite", "Poison", "Reptile"] },
  { word: "Train", forbidden: ["Tracks", "Thomas", "Choo", "Rail", "Engine"] },
  { word: "Ice", forbidden: ["Cold", "Water", "Freeze", "Cube", "Snow"] },
  { word: "Fire", forbidden: ["Hot", "Burn", "Flame", "Camp", "Red"] },
  { word: "Wind", forbidden: ["Air", "Blow", "Breeze", "Weather", "Storm"] }
].map(item => ({ ...item, difficulty: "easy" }));

const easyCategory = data.games.taboo.categories.find(c => c.id === 'easy');
easyCategory.items.push(...newWords);

fs.writeFileSync(file, JSON.stringify(data, null, 2));
console.log('Added ' + newWords.length + ' words');
